### ISSUE TITLE
Redone product categories

### ISSUE THREAD

**Issue by BorderITS** [borderitsolutions/amadaa#190]
Here is what is needed to make this work:

    pip install -r requirements.txt
    download jQuery UI from http://jqueryui.com/resources/download/jquery-ui-1.12.1.zip
    unzip the zip file you downloaded
    move the jquery UI folder into STATIC_ROOT/static

Hopefully that is all.

**Comment by lcabrini** [comment]
yee. does it work?

**Comment by lcabrini** [comment]
After the git reset you should be able to test this. You *may* need to do a git pull --force since your local repo is probably ahead of remote now.

Please test the new product category functionality. Note that there are currently no permission checks, so forget about that for now. Test the other functionality. If you think this style is better than the old one, then let's migrate product type and unit of measurement to use the same.

On the supplier side, I think the products subform should also be updated.

**Comment by BorderITS** [comment]
Closing this issue

**Comment by BorderITS** [comment]
Closing this issue
