### ISSUE TITLE
Normal user can change price wihtout giving permission 

### ISSUE THREAD

**Issue by BorderITS** [borderitsolutions/amadaa#234]

**Comment by lcabrini** [comment]
Yes, currently there are no permission checks here, because I'm not sure how the permissions should work. We have two different price fields, base price (price) and local (override) price. I'm not sure that it is the same two people that will have access to both prices.

As I see it, the global price (base price) would be set by somebody who has the authority to set prices for the company as a whole. Each branch manager should then have the permission to override this price for a particular branch.

This gets more complex however, because at the moment user's are not connected to branches. Since they are not connected to branches, how do we determine which branch the override price relates to? There is no way, until we have a link between a user and a branch.

**Comment by BorderITS** [comment]
Ok
