### ISSUE TITLE
Creating a customer

### ISSUE THREAD

**Issue by poeticabdul** [borderitsolutions/amadaa#283]
This model in the Customer app: 

class Customer(Contact):
    pass

 Inherits from the one below in the contact app: 

class Contact(models.Model):
    def __str__(self):
        try:
            return "{}, {}".format(self.person.last_name, 
                    self.person.first_name)
        except:
            return "{}".format(self.organization.name)

How does one create a Customer then? Contact model has no fields? 

Any help @lcabrini

**Comment by lcabrini** [comment]
The intended behavior is as follows:

1. Any "people" in the system inherit from Contact, so that it is possible to get a contact list of all "people".
2. Any "group of people" in the system inherit from Organization, so that it is possible to get a list of all "organizations"

Any fields that are common to all people, such as name, phone, email, address, etc. should go into the contact model. Any fields that is peculiar to a customer would go into the customer model. If there are no such fields, then at least one field is created for building the one-to-one relationship between the customer and the contact.

This is the model I worked out. But it is not set in stone. If you want/need to change it you can. But we should be able to:

1. have a contact list that contains all people and organizations in the system, whether clients, vendors, suppliers, contractors, staff, etc. Ideally in such a way that you don't have to query "people" and "organization" separatly, but could have a high level object called a contact, which could be either an organization or a person.

2. Be able to get a list of all customers, that is filtering away contacts that are not customers. The same would go for suppliers, vendors and other categories as well. Of course a part of the problem is "what is a customer?". Is a customer a person? Is a customer an organization? Could it be both? In order to make the application suitable for as many scenarios as possible, 'both' would be the best answer. But then our data model also has to support this, and ideally without asking the user to select company/person.

3. The data model, needs to be flexible enough to handle the above points and optimized enough not to cause long waiting times when updating information.

The contact model is supposed to have fields. First name, last name, email, phone, address, etc should be there.

**Comment by poeticabdul** [comment]
This explains a lot. Thanks

**Comment by lcabrini** [comment]
Cool. Let me know if there is anything else. All this really needs to get documented at some point

**Comment by poeticabdul** [comment]
Yeah, it needs some documentation
